-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKaIOfPaLljMpPbnW
af+oLFBZrelb3OLD3Gkr6YWEEhqgCgYIKoZIzj0DAQehRANCAARc4aTZKJXx+wsW
miE53yAElgo/dB4Xo08JVJXn6r2tvrkrJ2f5T/dcD3qatrVIX4NBPqSYV+CzpAkB
nmFKbcQu
-----END PRIVATE KEY-----